---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/metalmatze/kube-cockroachdb

steps:
  - name: build
    pull: always
    image: golang:1.14-alpine
    environment:
      GOPROXY: https://proxy.golang.org
    commands:
      - apk add -U git make
      - make build -o operator/api/v1alphav1/zz_generated.deepcopy.go
      - make test
      - make .tags
      - cp ./kubernetes.libsonnet ./operator/kubernetes.libsonnet
    when:
      event:
        - push
        - tag
        - pull_request

  - name: docker
    image: plugins/docker
    pull: always
    settings:
      context: operator
      dockerfile: operator/Dockerfile
      registry: quay.io
      repo: quay.io/metalmatze/kube-cockroachdb
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
---
kind: pipeline
name: monitoring

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/metalmatze/kube-cockroachdb

steps:
  - name: build
    pull: always
    image: golang:1.14-alpine
    environment:
      GOPROXY: https://proxy.golang.org
    commands:
      - apk add -U git jsonnet make
      - make monitoring/examples/prometheus.yaml --always-make
      - git diff --exit-code
